import User from "./User";
import Chat from './Chat';
import MessageEntity from './MessageEntity';
import Animation from "./Animation";
import Audio from './Audio';
import Document from "./Document";
import PhotoSize from "./PhotoSize";
import Sticker from "./Sticker";
import Video from "./Video";
import VideoNote from './VideoNote';
import Dice from "./Dice";
import Game from "./Game";
import Poll from "./Poll";
import Venue from "./Venue";
import Location from "./Location";
import MessageAutoDeleteTimerChanged from "./MessageAutoDeleteTimerChanged";
import { Invoice } from "./Invoice";
import SuccessfulPayment from "./SuccessfulPayment";
import ProximityAlertTriggered from "./ProximityAlertTriggered";
import VideoChatScheduled from "./VideoChatScheduled";
import VideoChatStarted from "./VideoChatStarted";
import VideoChatEnded from "./VideoChatEnded";
import VideoChatParticipantsInvited from "./VideoChatParticipantsInvited";
import WebAppData from "./WebAppData";
import InlineKeyboardMarkup from "./InlineKeyboardMarkup";

export default interface Message {
    message_id: number;
    from: User;
    sender_chat: Chat;
    date: number;
    chat: Chat;
    forward_from?: User;
    forward_from_chat?: Chat;
    forward_from_message_id?: number;
    forward_signature?: string;
    forward_sender_name?: string;
    forward_date?: number;
    is_automatic_forward?: number;
    reply_to_message?: Message;
    via_bot?: User;
    edit_date?: number;
    has_protected_content?: boolean;
    media_group_id?: string;
    author_signature?: string;
    text?: string;
    entities?: MessageEntity[];
    animation?: Animation;
    audio?: Audio;
    document?: Document;
    photo?: PhotoSize[];
    sticker?: Sticker;
    video?: Video;
    video_note?: VideoNote;
    voice?: Voice;
    caption?: string;
    caption_entities?: MessageEntity[];
    contact?: Contact;
    dice?: Dice;
    game?: Game;
    poll?: Poll;
    venue?: Venue;
    location?: Location;
    new_chat_members?: User[];
    left_chat_member?: User;
    new_chat_title?: string;
    new_chat_photo?: PhotoSize[];
    delete_chat_photo?: boolean;
    group_chat_created?: boolean;
    supergroup_chat_created?: boolean;
    chat_channel_created?: boolean;
    message_auto_delete_timer_changed?: MessageAutoDeleteTimerChanged;
    migrate_to_chat_id?: number;
    migrate_from_chat_id?: number;
    pinned_message?: Message;
    invoice?: Invoice;
    successful_payment?: SuccessfulPayment;
    connected_website?: string;
    passport_data?: PassportData;
    proximity_alert_triggered?: ProximityAlertTriggered;
    video_chat_scheduled?: VideoChatScheduled;
    video_chat_started?: VideoChatStarted;
    video_chat_ended?: VideoChatEnded;
    video_chat_participants_invited?: VideoChatParticipantsInvited;
    web_app_data?: WebAppData;
    reply_markup?: InlineKeyboardMarkup;
};